//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public int IDActividad { get; set; }
        public string NombreAct { get; set; }
        public string Descripcion { get; set; }
        public string Instructor { get; set; }
        public Nullable<System.DateTime> Horario { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Plazas { get; set; }
    }
}
