//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IDCliente { get; set; }
        public string NombreCli { get; set; }
        public string ApellidoCli { get; set; }
        public Nullable<int> TelefonoCli { get; set; }
        public string MailCli { get; set; }
        public string ContrasenaPerfil { get; set; }
        public Nullable<int> ReservasActivas { get; set; }
        public Nullable<int> ColaReserva { get; set; }
    }
}
